package com.liu.dao;

import com.liu.model.User;
import com.liu.model.UserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_t
	 * @mbggenerated  Fri Dec 22 15:54:34 CST 2017
	 */
	int countByExample(UserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_t
	 * @mbggenerated  Fri Dec 22 15:54:34 CST 2017
	 */
	int deleteByExample(UserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_t
	 * @mbggenerated  Fri Dec 22 15:54:34 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_t
	 * @mbggenerated  Fri Dec 22 15:54:34 CST 2017
	 */
	int insert(User record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_t
	 * @mbggenerated  Fri Dec 22 15:54:34 CST 2017
	 */
	int insertSelective(User record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_t
	 * @mbggenerated  Fri Dec 22 15:54:34 CST 2017
	 */
	int insertBatch(@Param("list") List<User> list);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_t
	 * @mbggenerated  Fri Dec 22 15:54:34 CST 2017
	 */
	List<User> selectByExample(UserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_t
	 * @mbggenerated  Fri Dec 22 15:54:34 CST 2017
	 */
	User selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_t
	 * @mbggenerated  Fri Dec 22 15:54:34 CST 2017
	 */
	int updateByExampleSelective(@Param("record") User record,
			@Param("example") UserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_t
	 * @mbggenerated  Fri Dec 22 15:54:34 CST 2017
	 */
	int updateByExample(@Param("record") User record,
			@Param("example") UserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_t
	 * @mbggenerated  Fri Dec 22 15:54:34 CST 2017
	 */
	int updateByPrimaryKeySelective(User record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_t
	 * @mbggenerated  Fri Dec 22 15:54:34 CST 2017
	 */
	int updateByPrimaryKey(User record);
}