package com.liu.model;

import java.io.Serializable;

public class User implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_t.id
	 * @mbggenerated  Fri Dec 22 15:54:34 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_t.user_name
	 * @mbggenerated  Fri Dec 22 15:54:34 CST 2017
	 */
	private String userName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_t.password
	 * @mbggenerated  Fri Dec 22 15:54:34 CST 2017
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_t.age
	 * @mbggenerated  Fri Dec 22 15:54:34 CST 2017
	 */
	private Integer age;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table user_t
	 * @mbggenerated  Fri Dec 22 15:54:34 CST 2017
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * @return  
	 * @mbggenerated  Fri Dec 22 15:54:34 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * @param id  
	 * @mbggenerated  Fri Dec 22 15:54:34 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * @return  
	 * @mbggenerated  Fri Dec 22 15:54:34 CST 2017
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * @param userName  
	 * @mbggenerated  Fri Dec 22 15:54:34 CST 2017
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}

	/**
	 * @return  
	 * @mbggenerated  Fri Dec 22 15:54:34 CST 2017
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * @param password  
	 * @mbggenerated  Fri Dec 22 15:54:34 CST 2017
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * @return  
	 * @mbggenerated  Fri Dec 22 15:54:34 CST 2017
	 */
	public Integer getAge() {
		return age;
	}

	/**
	 * @param age  
	 * @mbggenerated  Fri Dec 22 15:54:34 CST 2017
	 */
	public void setAge(Integer age) {
		this.age = age;
	}
}