package com.liu.model;

import java.io.Serializable;

public class User implements Serializable {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column user_t.id
     * @mbggenerated  Thu Jan 04 14:26:06 CST 2018
     */
    private Integer id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column user_t.user_name
     * @mbggenerated  Thu Jan 04 14:26:06 CST 2018
     */
    private String userName;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column user_t.password
     * @mbggenerated  Thu Jan 04 14:26:06 CST 2018
     */
    private String password;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column user_t.age
     * @mbggenerated  Thu Jan 04 14:26:06 CST 2018
     */
    private Integer age;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column user_t.head_image
     * @mbggenerated  Thu Jan 04 14:26:06 CST 2018
     */
    private String headImage;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column user_t.content
     * @mbggenerated  Thu Jan 04 14:26:06 CST 2018
     */
    private String content;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table user_t
     * @mbggenerated  Thu Jan 04 14:26:06 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * @return  
     * @mbggenerated  Thu Jan 04 14:26:06 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * @param id  
     * @mbggenerated  Thu Jan 04 14:26:06 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * @return  
     * @mbggenerated  Thu Jan 04 14:26:06 CST 2018
     */
    public String getUserName() {
        return userName;
    }

    /**
     * @param userName  
     * @mbggenerated  Thu Jan 04 14:26:06 CST 2018
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * @return  
     * @mbggenerated  Thu Jan 04 14:26:06 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * @param password  
     * @mbggenerated  Thu Jan 04 14:26:06 CST 2018
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * @return  
     * @mbggenerated  Thu Jan 04 14:26:06 CST 2018
     */
    public Integer getAge() {
        return age;
    }

    /**
     * @param age  
     * @mbggenerated  Thu Jan 04 14:26:06 CST 2018
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * @return  
     * @mbggenerated  Thu Jan 04 14:26:06 CST 2018
     */
    public String getHeadImage() {
        return headImage;
    }

    /**
     * @param headImage  
     * @mbggenerated  Thu Jan 04 14:26:06 CST 2018
     */
    public void setHeadImage(String headImage) {
        this.headImage = headImage;
    }

    /**
     * @return  
     * @mbggenerated  Thu Jan 04 14:26:06 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * @param content  
     * @mbggenerated  Thu Jan 04 14:26:06 CST 2018
     */
    public void setContent(String content) {
        this.content = content;
    }
}